services:
  api:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: nest-boilerplate-dev
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ../../env/env.develop 
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-dev
    restart: always
    env_file:
      - ../../env/env.develop 
    ports: 
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: {}